language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq wx-common libwxbase2.8-0 libwxgtk2.8-0 libwxbase2.8-dev libwxgtk2.8-dev libgtk2.0-dev libwx-perl
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
install:
  - "cpanm -n -v --installdeps ."
branches:
  only:
    - development
script: "prove t/frame.t"
notifications:
  email: false
