language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libwx-perl
install:
  - "cpanm -n --installdeps ."
branches:
  only:
    - development
script: "prove t/frame.t"
notifications:
  email: false
